version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
      time: "22:35"
      timezone: "Asia/Singapore"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "OpenTelemetry*"
    groups:
      nuget-dependencies:
        update-types:
          - "minor"
          - "patch"
